# Customer-Service
FROM openjdk:17
ARG JAR_FILE=target/*.jar
COPY target/Dphone_Customer_Service-0.0.1-SNAPSHOT.jar Dphone_Customer_Service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/Dphone_Customer_Service-0.0.1-SNAPSHOT.jar"]