# Referral-Service
FROM openjdk:17
ARG JAR_FILE=target/*.jar
COPY target/DphoneReferralService2-0.0.1-SNAPSHOT.jar DphoneReferralService2-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/DphoneReferralService2-0.0.1-SNAPSHOT.jar"]