# Customer-Service
FROM openjdk:17
ARG JAR_FILE=target/*.jar
COPY target/Dphone_Buying_Details-0.0.1-SNAPSHOT.jar Dphone_Buying_Details-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/Dphone_Buying_Details-0.0.1-SNAPSHOT.jar"]
EXPOSE 8083